### ISSUE TITLE
rs-dml

### ISSUE THREAD

**Issue by T4rr4g4** [timetravelthree/IDARustDemangler#2]
Hi!
This component fails me. Could you tell me what it is or how to install it.

..... plugins/IDARustDemangler.py", line 31, in __init__
assert len(self.rs_dml) > 0, "rs-dml is not installed on your system"

Thank you

**Comment by T4rr4g4** [comment]
Ok, I just saw it, sorry...

**Comment by imK3** [comment]
Hi! it fails me too.  I try to google and install this, but I didn't get anything useful. Could you tell me  how to install it. Thank you!

**Comment by timetravelthree** [comment]
Don't worry, I'll make the instructions clearer in the README.md for anyone who may encounter the same issue. To resolve it, simply go to https://github.com/timetravelthree/FTLRustDemangler and follow the installation instructions provided there.
